vhosts {
    default {
        port 80
        root /usr/share/go-tinyproxy/static

        security {
            frame_options SAMEORIGIN
            content_type nosniff
            xss_protection "1; mode=block"
        }
    }
}
