vhosts:
  example.com:
    port: 443
    root: /var/www/example
    compression: true
    security:
      headers:
        frame_options: "SAMEORIGIN"
        content_type: "nosniff"
        xss_protection: "1; mode=block"
        csp: "default-src 'self'"
        hsts: "max-age=31536000; includeSubDomains"
      rate_limit:
        enabled: true
        requests: 100
        window: 1m
      max_body_size: 10485760 # 10MB in bytes
